Dodanie Layout ( Ramy ) strony
Andrzej-Marek/car_service_base pull request #2
Opened 2020-11-11 18:23 UTC by tomaszprc

2020-11-11 18:26 UTC, tomaszprc commented
Jedynie taki mam błąd, mam z tym coś zrobić?

![image](https://user-images.githubusercontent.com/26138569/98849602-bf948800-2453-11eb-8c84-dfa030bae8b4.png)

2020-11-11 18:33 UTC, Andrzej-Marek commented on src/App.tsx
> +            <Container>
React always have to have only one child. So wrap all inside Container in empty <></>

2020-11-11 18:33 UTC, Andrzej-Marek commented on src/components/Container/Container.tsx
> +    children: JSX.Element
Don't pass children prop here, it's already in FC ( react ) type

2020-11-11 18:33 UTC, Andrzej-Marek commented on src/components/Container/Container.tsx
> +         max-width: 750px;
To increase UX just use padding: 10px 0 ( and more on bigger screens ) and set the width to 95vw ( and small or bigger screen ). Test how to resize flow works

2020-11-11 19:00 UTC, tomaszprc commented on src/components/Container/Container.tsx
> +         max-width: 750px;
Ok, I removed max-width from css and I created this one
![image](https://user-images.githubusercontent.com/26138569/98852737-6713b980-2458-11eb-8839-028d707cfb55.png)

I set smaller width on bigger screens. Is it correct?

2020-11-11 19:14 UTC, tomaszprc commented on src/components/Container/Container.tsx
> +         max-width: 750px;
To quote your message : " padding: 10px 0 " , it is style for padding-y (top,bottom) I think you thought padding-x (left and right). I will set the padding-y later in others components

2020-11-12 05:43 UTC, Andrzej-Marek requested changes

2020-11-12 05:43 UTC, Andrzej-Marek commented on src/App.tsx
> +                <>
Why you use <></> if you have only one child?

2020-11-12 05:43 UTC, Andrzej-Marek commented on src/App.tsx
> +    background: #E5E5E5;
use colors from theme ( check primary button example )

2020-11-12 05:43 UTC, Andrzej-Marek commented on src/components/Container/Container.tsx
> +        width: 75vw;
You don't have max width set.  set max width to 1200 px

2020-11-12 05:43 UTC, Andrzej-Marek commented on src/components/index.ts
> +//Container
Add comments when more than one it's importing from the folder. Like you have buttons folder and them more folders. If it is only one folder, then you don't have to type a comment

2020-11-12 20:04 UTC, Andrzej-Marek approved these changes

2020-11-12 20:04 UTC, merged