Do list dodać i18next
Andrzej-Marek/car_service_base pull request #5
Opened 2020-11-16 17:42 UTC by tomaszprc

2020-11-16 17:53 UTC, Andrzej-Marek requested changes

2020-11-16 17:53 UTC, Andrzej-Marek commented on src/containers/ServiceDetails/ServiceDetails.tsx
> +    const { t } = useTranslation(["tile"]);
1) you don't have to use array here.
2) Name it different, no tile. Make json something like carSpecification

2020-11-16 17:53 UTC, Andrzej-Marek commented on src/locales/pl/index.js
> +    tile
carSpecification

2020-11-16 17:53 UTC, Andrzej-Marek commented on src/components/Lists/CarDetailsList/CarDetailsList.tsx
> +    const { t } = useTranslation(["tile"]);
Why you're using array here? 
2) Make JSON that have a better name like carSpecification

2020-11-16 21:00 UTC, tomaszprc commented
Fixed

2020-11-17 20:45 UTC, Andrzej-Marek requested changes

2020-11-17 21:07 UTC, tomaszprc commented on src/components/Lists/CarDetailsList/CarDetailsList.tsx
> +                <ListElement label={t("carSpecification:carDetails.mark")} value="Mercedes Benz" />
fixed

2020-11-18 07:36 UTC, Andrzej-Marek approved these changes

2020-11-18 07:38 UTC, merged