Kafelka Serwis
Andrzej-Marek/car_service_base pull request #6
Opened 2020-11-16 21:34 UTC by tomaszprc

2020-11-16 21:35 UTC, tomaszprc commented on src/components/Lists/components/ListElement/ListElement.tsx
> -            <ListValue>{value ?? "-"}</ListValue>
What is mean this value: {value ?? "-"}

2020-11-17 05:57 UTC, Andrzej-Marek requested changes

2020-11-17 05:57 UTC, Andrzej-Marek commented on src/components/Lists/components/ListElement/ListElement.tsx
> +            <ListValue>{value ? value : children}</ListValue>
We don'y want to have children here. You can use ,,value || "-",,  or value ?? "-"

2020-11-17 05:57 UTC, Andrzej-Marek commented on src/components/Lists/components/ListElement/ListElement.tsx
> -            <ListValue>{value ?? "-"}</ListValue>
No null operator

2020-11-17 05:57 UTC, Andrzej-Marek commented on src/containers/ServiceDetails/ServiceDetails.tsx
> +            <ContentTile title="Serwis">
i18next

2020-11-17 05:57 UTC, Andrzej-Marek commented on src/locales/pl/serviceDetails.json
> +    "serviceDetails": {
If you have serviceDetails json, just for service details translations you don't have to create nested values.

You can use date, serviceNumber etc on main object

2020-11-17 20:42 UTC, Andrzej-Marek requested changes

2020-11-17 20:42 UTC, Andrzej-Marek commented on src/components/Lists/ServiceListInfo/ServiceListInfo.tsx
> +            <ListServiceElement label={t("service")} company="EXELO s.c" street="ul Pszczyńska 116" address="43-254 Warszowice"/>
We have 2 option here, just build it with <div> <ListElement /> (inside) </div>
Or create special component for company details. ( Better option ) but name ListServiceElement have nothing with company

Your options is not good

2020-11-17 21:05 UTC, tomaszprc commented on src/components/Lists/ServiceListInfo/ServiceListInfo.tsx
> +            <ListServiceElement label={t("service")} company="EXELO s.c" street="ul Pszczyńska 116" address="43-254 Warszowice"/>
Ok, I changed name of this component. I hope you didn't mean change localization of this component to ServiceListInfo/components/ListServiceElement as well, otherwise i can change it

2020-11-18 07:39 UTC, Andrzej-Marek approved these changes

2020-11-18 07:40 UTC, merged